# Generated by Django 3.2.6 on 2021-08-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
                ('num_of_eps', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('studio', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', models.ManyToManyField(to='anime.Genre')),
            ],
        ),
    ]
