# Generated by Django 3.2.6 on 2021-08-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='episode_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
