# Generated by Django 3.2.6 on 2021-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_episode_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='anime',
            name='cover_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='poster_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
