# Generated by Django 3.2.6 on 2021-08-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='anime', to='anime.Genre'),
        ),
    ]
