# Generated by Django 3.2.6 on 2021-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_anime_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['name_en']},
        ),
        migrations.AddField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='anime', to='anime.Character'),
        ),
    ]
