# Generated by Django 3.2.6 on 2021-08-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_auto_20210813_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='other_names',
            field=models.CharField(default='def', max_length=200),
            preserve_default=False,
        ),
    ]
