# Generated by Django 3.2.6 on 2021-08-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_auto_20210813_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
