# Generated by Django 3.2.6 on 2021-08-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_alter_character_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='other_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
