# Generated by Django 3.2.6 on 2021-08-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_alter_character_other_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='animes', to='anime.Genre'),
        ),
    ]
