# Generated by Django 3.2.6 on 2021-09-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_alter_anime_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['rating']},
        ),
    ]
