# Generated by Django 3.2.6 on 2021-09-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_alter_anime_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['name_en']},
        ),
    ]
