# Generated by Django 3.2.6 on 2021-09-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_auto_20210903_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='voice',
            new_name='voice_en',
        ),
        migrations.AddField(
            model_name='character',
            name='voice_jp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
